// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_API_TOKEN: string;
	STRIPE_SECRET_KEY: string;
	NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
	DB: D1Database;
}
