import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="font-poppins">
      {/* <Head>
        <title>Space Dynamic - SEO HTML5 Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      {/* Header */}
      <header className="sticky top-0 z-50 bg-white shadow-md">
        <nav className="container mx-auto px-4 py-4 flex justify-between items-center">
          <h4 className="text-2xl font-bold">
            Spac<span className="text-red-500">Dyna</span>
          </h4>

          <div className="hidden md:flex space-x-8 items-center">
            <a href="#top" className="text-gray-600 hover:text-red-500">
              Home
            </a>
            <a href="#about" className="text-gray-600 hover:text-red-500">
              About Us
            </a>
            <a href="#services" className="text-gray-600 hover:text-red-500">
              Services
            </a>
            <a href="#portfolio" className="text-gray-600 hover:text-red-500">
              Portfolio
            </a>
            <a href="#blog" className="text-gray-600 hover:text-red-500">
              Blog
            </a>
            <a href="#contact" className="text-gray-600 hover:text-red-500">
              Message Us
            </a>
            <button className="main-red-button">Contact Now</button>
          </div>
        </nav>
      </header>

      {/* Main Banner */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="flex flex-col lg:flex-row items-center">
            <div className="lg:w-1/2 mb-12 lg:mb-0">
              <h6 className="text-red-500 mb-4">Welcome to Space Dynamic</h6>
              <h1 className="text-4xl md:text-5xl font-bold mb-6">
                We Make <span className="text-red-500">Digital Ideas</span>{" "}
                &amp; SEO Marketing
              </h1>
              <p className="text-gray-600 mb-8">
                Space Dynamic is a professional looking HTML template using a
                Bootstrap 5...
              </p>
              <form className="flex flex-col space-y-4">
                <input
                  type="text"
                  placeholder="Your website URL..."
                  className="border p-3 rounded-lg"
                />
                <button className="main-red-button w-fit">Analyze Site</button>
              </form>
            </div>
            <div className="lg:w-1/2">
              <Image
                src="/assets/images/banner-right-image.png"
                alt="team meeting"
                width={600}
                height={400}
                className="w-full"
              />
            </div>
          </div>
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="flex flex-col lg:flex-row items-center gap-12">
            <div className="lg:w-1/3">
              <Image
                src="/assets/images/about-left-image.png"
                alt="person graphic"
                width={400}
                height={400}
              />
            </div>
            <div className="lg:w-2/3 grid grid-cols-1 md:grid-cols-2 gap-8">
              {[1, 2, 3, 4].map((item) => (
                <div
                  key={item}
                  className="flex items-center p-6 bg-white rounded-lg shadow-sm"
                >
                  <div className="w-16 mr-4">
                    <Image
                      src={`/assets/images/service-icon-0${item}.png`}
                      alt="service"
                      width={64}
                      height={64}
                    />
                  </div>
                  <div>
                    <h4 className="text-xl font-bold mb-2">Service Title</h4>
                    <p className="text-gray-600">
                      Lorem ipsum dolor sit amet...
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section id="services" className="py-20">
        <div className="container mx-auto px-4">
          <div className="flex flex-col lg:flex-row items-center gap-12">
            <div className="lg:w-1/2">
              <Image
                src="/assets/images/services-left-image.png"
                alt="services"
                width={500}
                height={500}
              />
            </div>
            <div className="lg:w-1/2">
              <h2 className="text-3xl font-bold mb-6">
                Grow your website with our{" "}
                <span className="text-red-500">SEO</span> service
              </h2>
              <div className="space-y-8">
                {[84, 88, 94].map((percentage, index) => (
                  <div key={index}>
                    <div className="flex justify-between mb-2">
                      <h4>Skill Name</h4>
                      <span>{percentage}%</span>
                    </div>
                    <div className="progress-bar">
                      <div
                        className="progress-fill"
                        style={{ width: `${percentage}%` }}
                      ></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Add remaining sections following similar patterns */}

      <footer className="bg-gray-800 text-white py-8">
        <div className="container mx-auto px-4 text-center">
          <p>© Copyright 2021 Space Dynamic Co. All Rights Reserved.</p>
        </div>
      </footer>
    </div>
  );
}
